version: '3.4'

services:
  solucaoerpauth:
    image: ${DOCKER_REGISTRY-}solucaoerpauth
    build:
      context: .
      dockerfile: SolucaoErpAuth/Dockerfile

  solucaoerp:
    image: ${DOCKER_REGISTRY-}solucaoerp
    build:
      context: .
      dockerfile: SolucaoErp/Dockerfile

