// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDePreco.Repository;

#nullable disable

namespace RegistroDePreco.Migrations
{
    [DbContext(typeof(RegistroPrecoContext))]
    [Migration("20230815145254_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RegistroDePreco.Model.RegistroPreco", b =>
                {
                    b.Property<Guid>("codRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("pdvId")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("produtoId")
                        .HasColumnType("int");

                    b.HasKey("codRegistro");

                    b.HasIndex("pdvId");

                    b.HasIndex("produtoId");

                    b.ToTable("RegistroPreco", (string)null);
                });

            modelBuilder.Entity("SolucaoErpDomain.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("SolucaoErpDomain.Model.ExtratoDePonto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoEvento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("TipoExtrato")
                        .HasColumnType("int");

                    b.Property<Guid>("Usuario")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Usuario");

                    b.ToTable("ExtratoDePonto", (string)null);
                });

            modelBuilder.Entity("SolucaoErpDomain.Model.Pdv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Pdv", (string)null);
                });

            modelBuilder.Entity("SolucaoErpDomain.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("codEvento")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("RegistroDePreco.Model.RegistroPreco", b =>
                {
                    b.HasOne("SolucaoErpDomain.Model.Pdv", "pdv")
                        .WithMany()
                        .HasForeignKey("pdvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolucaoErpDomain.Model.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pdv");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("SolucaoErpDomain.Model.Produto", b =>
                {
                    b.HasOne("SolucaoErpDomain.Model.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
